tunnel: retrogg

metrics: localhost:38531
originRequest:
  # Set this to your root CA
  # This one is selfsigned
  caPool: "/etc/cloudflared/RootCert.crt"

ingress:
  - hostname: retrogg.trudev.tech
    service: https://nginx:443
  - service: http_status:404